version: '3.1'
networks:
  default:
    name: kong-net
volumes:
  conf:
  vhost:
  html:
  dhparam:
  certs:
  acme:
services:
#region Kong Gateway
  kong:
    image: kong:alpine
    hostname: kong
    container_name: kong
    environment:
      KONG_DATABASE: 'off'
      KONG_PROXY_ACCESS_LOG: '/dev/stdout'
      KONG_ADMIN_ACCESS_LOG: '/dev/stdout'
      KONG_PROXY_ERROR_LOG: '/dev/stderr'
      KONG_ADMIN_ERROR_LOG: '/dev/stderr'
      KONG_ADMIN_LISTEN: "0.0.0.0:8001, 0.0.0.0:8444 ssl"
      KONG_DECLARATIVE_CONFIG: "/opt/kong/kong.yaml"
    command: "kong start"
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
    volumes:
    - ./config:/opt/kong
#endregion Kong Gateway

#region Micro-service Products
  micro-products:
    image: micro-products
    container_name: micro-products
    hostname: micro-products
    restart: always
    ports:
      - 3001:3001
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://root:root@mongo:27017/products?authSource=admin
#endregion Micro-service Comments

#region Micro-service Comments
  micro-comments:
    image: micro-comments
    container_name: micro-comments
    restart: always
    ports:
      - 3002:3002
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://root:root@mongo:27017/comments?authSource=admin
#endregion Micro-service Comments

#region Micro-service Product-List
  micro-product-lists:
    image: micro-product-lists
    container_name: micro-product-lists
    restart: always
    ports:
      - 3003:3003
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://root:root@mongo:27017/product-lists?authSource=admin
#endregion Micro-service Product-List

#region Micro-service User
  micro-users:
    image: micro-users
    container_name: micro-users
    restart: always
    ports:
      - 3004:3004
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://root:root@mongo:27017/users?authSource=admin
#endregion Micro-service User

#region Micro-service Rating
  micro-ratings:
    image: micro-ratings
    container_name: micro-ratings
    restart: always
    ports:
      - 3005:3005
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://root:root@mongo:27017
#endregion Micro-service Rating

#region Micro-service Order
  micro-orders:
    image: micro-orders
    container_name: micro-orders
    restart: always
    ports:
      - 3006:3006
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/orders
      - MONGO_USER=root
      - MONGO_PASSWORD=root
      - DB=orders
      - PORT=3006
      - APP_ENV=development
#endregion Micro-service Order

#region Front
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    volumes_from:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro

  web:
    image: web
    container_name: web
    restart: always
    ports:
      - 80:80
    environment:
      - NEXTAUTH_URL=http://localhost:80
      - NEXT_PUBLIC_GATEWAY_URL=http://localhost:8000
      - JWT_SECRET=B9827D4B21956C48A68C0DF76EAEE7CFA1350A7F27A080E01273FD71E5D23003
      - VIRTUAL_HOST=vps-e49d92d7.vps.ovh.net
      - LETSENCRYPT_HOST=vps-e49d92d7.vps.ovh.net
#endregion Front

#region Database
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
        - 27017:27017
    environment: 
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: root
#endregion Database